### PR TITLE
PR: Multi Uploader breaks when Upload fails

### LINKED ISSUE #36: Multi Uploader breaks when Upload fails
To reproduce just try uploading an SVG file.

At first glance it seems as if the response from `async-upload.php` is assumed to always be an image, while this can also be an error message if the upload fails. This is then put in the template where the `` is expected breaking the template somehow.

### PR DESCRIPTION
**Pull request by kraftner**
fixes #36

### CODE REVIEW

**Comment by kraftner** [comment]
This still lacks the built assets which is currently blocked by a broken build process. See #27

**Comment by franz-josef-kaiser** [comment]
@kraftner After #27 is tested, `issue-27-assets` needs to get `--no-ff` merged into `kraftner/issue/36` to proceed here.

**Comment by franz-josef-kaiser** [comment]
@kraftner Did the update from `issue-27-assets` to the `kraftner/issue/36` branch. Runs smoothly for me `npm install && npm run build`, but please double check with the goals for this PR. Thanks in advance!

**Comment by kraftner** [comment]
Okay, I rebased this on dev and gave it a test run. I think everything should be ready for merge: :tada:

**Comment by franz-josef-kaiser** [comment]
On Friday nights, I blindly trust you @kraeftner

**Pull request merged**
